import asyncio
import httpx
import json
import sys

# Ensure utf-8 output for windows terminal
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

API_URL = "http://localhost:8000"

async def test_cholera():
    print("Testing Cholera Prediction implementation...")
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        # 1. Test risk detection for a cholera hotspot
        print("\n1. Testing risk detection for Plateau (hotspot)...")
        try:
            resp = await client.get(f"{API_URL}/test-risk?lga=Plateau")
            data = resp.json()
            print(f"Risk for Plateau: {data.get('risk')}")
            if data.get('risk') == "HIGH":
                print("[OK] Success: Hotspot detected.")
            else:
                print("[FAIL] Hotspot not detected.")
        except Exception as e:
            print(f"Error testing hotspot: {e}")

        # 2. Test user registration and and message generation
        print("\n2. Testing user registration and health message generation...")
        try:
            # Use a unique phone to avoid "already registered" error
            import time
            unique_phone = int(time.time()) % 1000000000
            reg_resp = await client.post(f"{API_URL}/register", json={
                "name": "Cholera Tester",
                "phone": unique_phone,
                "lga": "Plateau",
                "password": "password123"
            })
            user = reg_resp.json()
            if 'id' not in user:
                print(f"[FAIL] Registration failed: {user}")
                return
                
            user_id = user['id']
            print(f"Created test user: {user_id}")
            
            # Test generate-message
            msg_resp = await client.post(f"{API_URL}/generate-message?user_id={user_id}")
            msg_data = msg_resp.json()
            script = msg_data.get('script', "").lower()
            print(f"Generated script snippet: {script[:100]}...")
            
            if script:
                 print("[OK] Script generated by AI.")
            else:
                 print("[FAIL] Script generation failed.")
                 
            # 3. Test symptom logging with new symptoms
            print("\n3. Testing symptom logging (diarrhea/vomiting)...")
            symp_resp = await client.post(f"{API_URL}/symptoms", json={
                "user_id": user_id,
                "fever": 1,
                "diarrhea": 1,
                "vomiting": 1,
                "notes": "Testing cholera symptoms"
            })
            symp_data = symp_resp.json()
            if symp_data.get('symptom', {}).get('diarrhea') == 1 and symp_data.get('symptom', {}).get('vomiting') == 1:
                print("[OK] Success: Diarrhea and Vomiting logged correctly.")
            else:
                print(f"[FAIL] Symptoms not saved correctly. Data: {symp_data}")
                
            # 4. Check health score impact
            print("\n4. Testing health score impact...")
            me_resp = await client.get(f"{API_URL}/me/{user_id}")
            me_data = me_resp.json()
            score = me_data.get('health_score', 100)
            print(f"Health score for symptomatic user: {score}%")
            if score < 50:
                 print("[OK] Success: Health score correctly reduced.")
            else:
                 print(f"[FAIL] Health score too high ({score}).")

        except Exception as e:
            print(f"Error during verification: {e}")

if __name__ == "__main__":
    asyncio.run(test_cholera())
